package code.name.monkey.retromusic.util

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import code.name.monkey.retromusic.R
import code.name.monkey.retromusic.glide.audiocover.AudioFileCover
import com.bumptech.glide.Glide
import com.bumptech.glide.load.resource.bitmap.RoundedCorners
import java.io.File

object AutoGeneratedPlaylistBitmap {
    fun getBitmap(
        context: Context, songPlaylist: List<code.name.monkey.retromusic.model.Song>?
    ): Bitmap? {
        if (songPlaylist == null || songPlaylist.isEmpty()) return getDefaultBitmap(context)
        if (songPlaylist.size == 1) return getBitmapWithSongPath(context, songPlaylist[0].data)
        val seenPaths = mutableSetOf<String>()
        val art: MutableList<Bitmap> = ArrayList()
        for (song in songPlaylist) {
            if (seenPaths.contains(song.data)) continue
            seenPaths.add(song.data)
            val bitmap = getBitmapWithSongPath(context, song.data)
            if (bitmap != null) art.add(bitmap)
            if (art.size == 9) break
        }
        return MergedImageUtils.joinImages(art)
    }

    private fun getBitmapWithSongPath(context: Context, path: String): Bitmap? {
        return try {
            Glide.with(context)
                .asBitmap()
                .transform(RoundedCorners(20))
                .load(AudioFileCover(path))
                .submit(200, 200)
                .get()
        } catch (e: Exception) {
            null
        }
    }

    private fun getDefaultBitmap(context: Context): Bitmap {
        return BitmapFactory.decodeResource(context.resources, R.drawable.default_album_art)
    }
}
